name: Fetch

on:
  workflow_dispatch: 

jobs:
  run-tests:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Execute Fetch Data Script
        env:
          BEARER_TOKEN: ${{ secrets.GITHUB_TOKEN}} 
        shell: pwsh
        run: |
          ./scripts/FetchData.ps1
          git commit -m "Fetching the week's pull requsts and issues and releases"
          git push
    
      - name: Create pull request
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_year=$(date +"%Y")
          current_week=$(date +"%V")
          branch_name="year/$current_year/week/$current_week"
          title="Year: $current_year Week: $current_week"
          gh pr create --title $title --body 'Created by Github action 🤖' --assignee spoo-bar --base main --head $branch_name --draft